default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database, :password) %>
  socket: /tmp/mysql.sock
  database: <%= Rails.application.class.module_parent_name.underscore %>_development

test:
  <<: *default
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database, :password) %>
  socket: /tmp/mysql.sock
  database: <%= Rails.application.class.module_parent_name.underscore %>_test
